<!DOCTYPE html>

<html>

<head>

    <meta charset="UTF-8">

    <title>Cash Flow Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #101828;
        }

        h1 {
            margin: 0 0 4px;
            font-size: 20px;
        }

        .company {
            margin-bottom: 4px;
            font-size: 12px;
            font-weight: bold;
        }

        .meta {
            margin-bottom: 18px;
        }

        .summary-table {
            width: 100%;
            margin-bottom: 18px;
            border-collapse: collapse;
        }

        .summary-table td {
            width: 33.33%;
            padding: 10px;
            border: 1px solid #D0D5DD;
        }

        .summary-label {
            margin-bottom: 5px;
            font-size: 9px;
            color: #667085;
        }

        .summary-value {
            font-size: 16px;
            font-weight: bold;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;
        }

        .report-table th,
        .report-table td {
            padding: 7px;
            border: 1px solid #D0D5DD;
            text-align: left;
        }

        .report-table th {
            background: #F2F4F7;
            font-weight: bold;
        }

        .opening-row {
            background: #F9FAFB;
        }

        .closing-row {
            font-weight: bold;
        }

        .transaction-code {
            margin-top: 2px;
            font-size: 8px;
            color: #667085;
        }
    </style>

</head>

<body>


    <h1>Cash Flow Report</h1>

    <div class="company">
        Syedn Tech Solutions
    </div>


    <div class="meta">

        Period:
        {{ $from->format('j F Y') }}
        -
        {{ $to->format('j F Y') }}

        <br>

        Generated on:
        {{ now()->format('j F Y') }}

        <br>

        Generated by:
        {{ auth()->user()->username ?? (auth()->user()->fullname ?? 'Admin') }}

    </div>


    <table class="summary-table">

        <tr>

            <td>

                <div class="summary-label">
                    Total Cash In
                </div>

                <div class="summary-value">
                    RM {{ number_format($totalCashIn, 2) }}
                </div>

            </td>


            <td>

                <div class="summary-label">
                    Total Cash Out
                </div>

                <div class="summary-value">
                    RM {{ number_format($totalCashOut, 2) }}
                </div>

            </td>


            <td>

                <div class="summary-label">
                    Net Cash Flow
                </div>

                <div class="summary-value">
                    RM {{ number_format($netCashFlow, 2) }}
                </div>

            </td>

        </tr>

    </table>


    <table class="report-table">

        <thead>

            <tr>

                <th>Subject</th>
                <th>Category</th>
                <th>Date</th>
                <th>Cash In</th>
                <th>Cash Out</th>
                <th>Balance</th>

            </tr>

        </thead>


        <tbody>

            <tr class="opening-row">

                <td>
                    Opening Balance
                </td>

                <td>
                    Opening Balance
                </td>

                <td>
                    {{ $from->format('j F Y') }}
                </td>

                <td>-</td>

                <td>-</td>

                <td>
                    RM
                    {{ number_format($openingBalance, 2) }}
                </td>

            </tr>


            @foreach ($reportRows as $row)
                @php

                    $cashFlow = $row['cashFlow'];

                    $category = $cashFlow->category?->category_name ?? '-';

                    if ($cashFlow->other_category) {
                        $category .= ' - ' . $cashFlow->other_category;
                    }

                @endphp


                <tr>

                    <td>

                        {{ $cashFlow->subject }}

                        <div class="transaction-code">
                            {{ $cashFlow->transaction_code }}
                        </div>

                    </td>


                    <td>
                        {{ $category }}
                    </td>


                    <td>
                        {{ $cashFlow->transaction_date->format('j F Y') }}
                    </td>


                    <td>

                        @if ($cashFlow->type === 'Cash In')
                            RM
                            {{ number_format($cashFlow->amount, 2) }}
                        @else
                            -
                        @endif

                    </td>


                    <td>

                        @if ($cashFlow->type === 'Cash Out')
                            RM
                            {{ number_format($cashFlow->amount, 2) }}
                        @else
                            -
                        @endif

                    </td>


                    <td>

                        RM
                        {{ number_format($row['balance'], 2) }}

                    </td>

                </tr>
            @endforeach


            <tr class="closing-row">

                <td colspan="3">

                    Closing Balance —
                    {{ $to->format('j F Y') }}

                </td>

                <td>
                    RM
                    {{ number_format($totalCashIn, 2) }}
                </td>

                <td>
                    RM
                    {{ number_format($totalCashOut, 2) }}
                </td>

                <td>
                    RM
                    {{ number_format($closingBalance, 2) }}
                </td>

            </tr>

        </tbody>

    </table>


</body>

</html>
